steps:
- name: 'maven:3.8.4-openjdk-11'
  entrypoint: 'mvn'
  args: ['-Dmaven.compiler.source=11', '-Dmaven.compiler.target=11','clean', 'install']
  dir: 'springboot-gcp-assignment-main/springboot-gcp-assignment-main'
  env:
    - 'JAVA_HOME=docker.io/library/maven:3.8.4-openjdk11'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  dir: 'springboot-gcp-assignment-main/springboot-gcp-assignment-main'
