steps:
- name: 'maven:3.8.4-openjdk-17'
  entrypoint: 'mvn'
  args: ['-Dmaven.compiler.source=17', '-Dmaven.compiler.target=17', 'clean', 'install']
  dir: 'springboot-gcp-assignment-main/springboot-gcp-assignment-main
  env:
    - 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-17-openjdk-amd64/bin'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  dir: 'springboot-gcp-assignment-main/springboot-gcp-assignment-main'
