steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/orbital-broker-407106/maven-image:latest']

- name: 'gcr.io/orbital-broker-407106/maven-image:latest'
  entrypoint: 'mvn'
  args: ['-Dmaven.compiler.source=17', '-Dmaven.compiler.target=17', 'clean', 'install']
  dir: 'springboot-gcp-assignment-main/springboot-gcp-assignment-main'
  env:
  - 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  dir: 'springboot-gcp-assignment-main/springboot-gcp-assignment-main'



