steps:
  - name: 'maven:3.8.4-openjdk-17'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH
      mvn clean install
  dir: 'springboot-gcp-assignment-main/springboot-gcp-assignment-main'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  dir: 'springboot-gcp-assignment-main/springboot-gcp-assignment-main'
