steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'create', '--region', 'us-central1']
  dir: 'springboot-gcp-assignment-main/springboot-gcp-assignment-main'
- name: 'maven:3.8.4-openjdk-17'
  entrypoint: 'mvn'
  args: ['clean', 'install']
  dir: 'springboot-gcp-assignment-main/springboot-gcp-assignment-main'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  dir: 'springboot-gcp-assignment-main/springboot-gcp-assignment-main'
